#!/bin/bash
set -e

echo "Beginning setup..."

# Make sure there is not an old virtualenv out there for this repo
./do/cleanup

# create virtual environment with requirements
python3 -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt

if [ "$(uname -s)" == "Linux" ]; then
  chmod 755 .venv/bin/*
fi

ansible-galaxy install -r ansible/roles/requirements.yml -p ansible/roles/external_roles

echo "Setup done"