  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ item.vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ root_volume_aggregate }}"
      size: "{{ item.size }}"
      size_unit: "{{ item.unit }}"
      percent_snapshot_space: 0
      space_guarantee: none
      efficiency_policy: default
      volume_security_style: ntfs
      junction_path: "/{{ item.vol_name }}"
      hostname: "{{ hostname }}"
      username: "HY-VEE\\{{ ansible_service_account }}"
      password: "{{ ansible_password }}"
      https: true
      validate_certs: false
    delegate_to: localhost
    with_items: "{{ vars_vol }}"